<a href="https://colab.research.google.com/github/sasikirankakara001/tensorflow/blob/master/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow

In [3]:
pip install tensorflow 

In [4]:
pip install tf-nightly

     |████████████████████████████████| 517.6MB 30kB/s 
     |████████████████████████████████| 460kB 45.8MB/s 
     |████████████████████████████████| 3.0MB 37.9MB/s 


In [5]:
pip install tensorflow-gpu

     |████████████████████████████████| 421.8MB 36kB/s 
     |████████████████████████████████| 450kB 38.7MB/s 
     |████████████████████████████████| 3.9MB 42.4MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=226c7b03ef212b0b892701276b4c95da7f5f060a0b7a807832257c19c1eaed2c
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tf-nightly 2.2.0.dev20200412 has requirement gast==0.3.3, but you'll have gast 0.2.2 which is incompatible.
ERROR: tensorflow 2.2.0rc2 has requirement gast==0.3.3, but you'll have gast 0.2.2 which is incompatible.
ERROR: tensorflow 2.2.0rc2 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 2.1.1 which is incompatible.
ERROR: tensorflow 2.2.0rc2 has requirement tensorflow-estimator<2.3.0,>=2.2.0rc0, but you'll have tensorflow-estimator 2.1.0 which is incompatible.
  Found existing installation: tensorflow-estimator 2.2.0rc

In [6]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow_core._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v2/version/__init__.py'>


In [0]:
string = tf.Variable("this is a string",tf.string)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.567,tf.float64)

In [0]:
rank1_tensor = tf.Variable(["Test"],tf.string)
rank2_tensor = tf.Variable([["test","ok"],["test","yes"]],tf.string)


In [13]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [16]:
rank2_tensor.shape

TensorShape([2, 2])

In [17]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [21]:
tensor2 = tf.reshape(tensor1,[2,3,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [23]:
tensor3 = tf.reshape(tensor2,[3,-1])
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [27]:
import numpy as np
a = np.arange(10).reshape(2,5)
tensor = tf.Variable(a,dtype=tf.int32)
print(tf.rank(tensor))
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
(2, 5)


In [28]:
three = tensor[0,2]
print(three)

tf.Tensor(2, shape=(), dtype=int32)
